name: Bug report
description: Report an issue/bug
labels: ["bug"]
body:
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you playing on?
      placeholder: "1.21"
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      description: What version of the mod are you using?
      placeholder: "0.0.1"
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod loader
      options:
        - Please select
        - NeoForge
        - Fabric
        - Other
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod loader version
      description: What version of NeoForge/Fabric are you using?
      placeholder: "0.0.1"
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Please describe what happened and what you expected to happen.
      placeholder: "Describe the bug here."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please explain what can to be done to cause the bug.
      placeholder: |
        Example:

        1. Press the local channel hotkey.
        2. Make sure there is at least one player within range.
        3. Type a message in chat.
        ...
  - type: textarea
    id: log-file
    attributes:
      label: Log file
      description: Please attach your latest.log file or upload it to [gists](https://gist.github.com/) / [pastebin](https://pastebin.com/) and paste a link to it here.
      placeholder: "Drag and drop your latest.log file here."
