modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/rikkamus/client-chat-channels/issues"
license = "MIT"

[[mods]]
modId = "clientchatchannels"
version = "${version}"
displayName = "Client Chat Channels"
displayURL = "https://github.com/rikkamus/client-chat-channels"
authors = "rikkamus"
description = "Adds client-side chat channels to the game."
logoFile = "icon.png"
updateJSONURL = "https://api.modrinth.com/updates/rzPe21Zl/forge_updates.json?neoforge=only"

[[dependencies.clientchatchannels]]
modId = "neoforge"
type = "required"
versionRange = "[21.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.clientchatchannels]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6, 1.22)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.clientchatchannels]]
modId="cloth_config"
type = "optional"
versionRange="[19.0.146,)"
ordering="AFTER"
side="CLIENT"
